### ISSUE TITLE
Formatter removes trailing newline

### ISSUE THREAD

**Issue by elenakrittik** [binhtran432k/ungrammar-language-features#89]
It's common for code and other code-like formats to allow trailing newlines, and many formats, especially those intended for humans to read and write, actually encourage adding trailing newlines. Currently, the formatter goes against this "convention" of sorts, and it would be great if it didn't.

**Comment by binhtddev** [comment]
The current implementation of formatter is based on the [rust.ungram](https://github.com/rust-analyzer/ungrammar/blob/master/rust.ungram) and [ungrammar.ungram](https://github.com/rust-analyzer/ungrammar/blob/master/ungrammar.ungram). There are some limitations for now because it force to merge comment and remove trailing newline. You can disable it through settings if you do not satisfy with the implementation.

In addition, I think ungrammar is very useful to describe and develop DSL for your own language. However, when your language is stable enough (just like rust-analyzer), then you will rarely edit it again. I think I will keep the implementation as it is and wait for the standard ungrammar formatter.
